### ISSUE TITLE
is there a demo?

### ISSUE THREAD

**Issue by francqz31** [GalaxyCong/StyleDubber#1]
hey there , is there a demo or a project page of the results?

**Comment by GalaxyCong** [comment]
Yes, StyleDubber equips a project page. My colleague is responsible for updating and publishing. I focus on this repository to release source code and model. 

We will notify you when the project page is updated!

**Comment by GalaxyCong** [comment]
Here is some demo: 

https://github.com/user-attachments/assets/e2ea24ca-7d64-4106-8d8e-3ab100bca1d7


https://github.com/user-attachments/assets/10da1ecc-27e9-4f6c-a133-535b28475b57




Setting3: 



Input Reference audio: 



https://github.com/user-attachments/assets/2b669e4a-8733-43ab-93be-490264e8f40e


Input Text: 

“Everyone's gonna love these new portion sizes.”


Input Video: 



https://github.com/user-attachments/assets/19ad6511-847f-447c-9b4e-0943883d815a



Result:


https://github.com/user-attachments/assets/e54a7b9d-9c4d-49c9-9032-021066016099

**Comment by GalaxyCong** [comment]
https://acl2024x.github.io/StyleDubber/
